# Generated by Django 3.2.8 on 2021-12-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_skd', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_stock', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_desc', models.CharField(max_length=240)),
            ],
        ),
    ]
