# Generated by Django 3.2.8 on 2021-12-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211211_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_img',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(default=1, upload_to='media/products_images/'),
            preserve_default=False,
        ),
    ]
